
# Site settings
title: Wuyunga
name: Yunga Wu
subtitle: Underwater Lab, SIA
email: wuyunga@sia.cn
description: >
  Underwater Lab, SIA
baseurl: ""
url: "https://yunga-wu.github.io/"
github_username:  Yunga-Wu
disqus_baseurl: "https://yunga-wu.github.io/"
disqus_shortname: https-yunga-wu-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yunga Wu"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Yunga-Wu
    url: https://github.com/yunga-wu
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://linkedin.com
    desc: Connect with me on LinkedIn
    share: true
